# Generated by Django 4.0.1 on 2022-01-19 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(blank=True, max_length=100)),
                ('category', models.IntegerField(blank=True)),
                ('availability', models.BooleanField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('price_on_sale', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('sale', models.BooleanField()),
                ('owner', models.TextField(max_length=100)),
                ('unit', models.TextField(max_length=10)),
                ('name', models.TextField(max_length=100)),
                ('quantity_stock', models.IntegerField()),
                ('quantity_sold', models.IntegerField()),
            ],
        ),
    ]
