# Generated by Django 3.2.8 on 2022-01-20 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateField(default='2022-01-20 12:46:36.367245'),
        ),
    ]
